export { CrmShell } from "./CrmShell";
export { CrmRouteGuard } from "./CrmRouteGuard";
export { CrmDashboardPage } from "./DashboardPage";
export { CrmCustomersPage } from "./CustomersPage";
export { CrmCustomerFormPage } from "./CrmCustomerFormPage";
export { Customer360Page } from "./Customer360Page";
export { CrmOrdersPage } from "./OrdersPage";
export { IdentityConflictsPage as CrmIdentityConflictsPage } from "./IdentityConflictsPage";
export { IdentityConflictsGuidePage as CrmIdentityConflictsGuidePage } from "./IdentityConflictsGuidePage";
export { ComplaintsPage as CrmComplaintsPage } from "./ComplaintsPage";
export { ComplaintDetailPage as CrmComplaintDetailPage } from "./ComplaintDetailPage";
export { ComplaintsGuidePage as CrmComplaintsGuidePage } from "./ComplaintsGuidePage";
export { GroupsPage as CrmGroupsPage } from "./GroupsPage";
export { OccasionsPage as CrmOccasionsPage } from "./OccasionsPage";
export { GroupProfilePage as CrmGroupProfilePage } from "./GroupProfilePage";
export { GroupsAnalyticsPage as CrmGroupsAnalyticsPage } from "./GroupsAnalyticsPage";
export { GroupsSmartSegmentsPage as CrmGroupsSmartSegmentsPage } from "./GroupsSmartSegmentsPage";
export { CrmStaffPermissionsPage } from "./CrmStaffPermissionsPage";
export { CrmSettingsPage } from "./CrmSettingsPage";
export { CrmReportsPage } from "./CrmReportsPage";
export { CrmReportsRevenuePage } from "./CrmReportsRevenuePage";
export { LoyaltyPage as CrmLoyaltyPage } from "./LoyaltyPage";
