export { CrmShell } from "./CrmShell";
export { CrmRouteGuard } from "./CrmRouteGuard";
export { CrmDashboardPage } from "./DashboardPage";
export { CrmCustomersPage } from "./CustomersPage";
export { CrmCustomerFormPage } from "./CrmCustomerFormPage";
export { Customer360Page } from "./Customer360Page";
export { CrmOrdersPage } from "./OrdersPage";
export { IdentityConflictsPage as CrmIdentityConflictsPage } from "./IdentityConflictsPage";
export { ComplaintsPage as CrmComplaintsPage } from "./ComplaintsPage";
export { GroupsPage as CrmGroupsPage } from "./GroupsPage";
export { OccasionsPage as CrmOccasionsPage } from "./OccasionsPage";
export { GroupProfilePage as CrmGroupProfilePage } from "./GroupProfilePage";
export { LoyaltyPage as CrmLoyaltyPage } from "./LoyaltyPage";
