import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Bike, Boxes, Clock3, Gauge, Loader2, PackageCheck, RefreshCw, ShieldAlert, Truck, UserRoundCheck, X } from "lucide-react";
import { operationsService, type AlertSeverity, type OperationalRole, type OperationsDashboardResponse, type OperationsOrder, type OperationsStage } from "../../services/operationsService";
import { orderService } from "../../services/orderService";
import { toast } from "../shared/Toast";

const THRESHOLDS = { readyWarning: 5, deliveryWarning: 30, deliveryCritical: 45, activeLate: 60 } as const;
const STAGES: Array<{ key: OperationsStage; label: string; accent: string }> = [
  { key: "PREPARATION", label: "قيد التحضير", accent: "border-sky-500" },
  { key: "READY_FOR_DELIVERY", label: "جاهز للدليفري", accent: "border-amber-400" },
  { key: "OUT_FOR_DELIVERY", label: "خارج للتوصيل", accent: "border-violet-400" },
  { key: "DELIVERED", label: "تم التسليم", accent: "border-emerald-400" },
  { key: "CANCELLED", label: "ملغي", accent: "border-rose-500" },
];
const ROLE_LABEL: Record<OperationalRole, string> = { call_center_agent: "كول سنتر", cashier: "كاشير", assembler: "مجمّع طلبات", delivery_driver: "دليفري" };
const VEHICLE_LABEL: Record<string, string> = { bicycle: "دراجة", electric_bike: "دراجة كهربائية", motorcycle: "دراجة نارية", external: "مندوب خارجي", external_driver: "مندوب خارجي" };
const today = () => new Date().toLocaleDateString("en-CA");
const minutesSince = (date?: string | null) => date ? Math.max(0, Math.floor((Date.now() - Date.parse(date)) / 60000)) : 0;
const minutesBetween = (from?: string | null, to?: string | null) => from && to ? Math.max(0, Math.floor((Date.parse(to) - Date.parse(from)) / 60000)) : null;
const getStage = (o: OperationsOrder): OperationsStage => o.stage ?? (o.status === "PREPARATION" && o.assembled_at ? "READY_FOR_DELIVERY" : o.status as OperationsStage);
const getTimer = (o: OperationsOrder) => { const stage = getStage(o); if (stage === "DELIVERED") return minutesBetween(o.created_at, o.delivered_at); if (stage === "CANCELLED") return minutesBetween(o.created_at, o.cancelled_at); if (stage === "OUT_FOR_DELIVERY") return minutesSince(o.delivery_started_at); if (stage === "READY_FOR_DELIVERY") return minutesSince(o.assembled_at); return minutesSince(o.created_at); };
const getTimerLabel = (o: OperationsOrder) => ["DELIVERED", "CANCELLED"].includes(getStage(o)) ? "المدة الإجمالية" : "زمن المرحلة";
const risk = (o: OperationsOrder): AlertSeverity | null => { const m = getTimer(o) ?? 0, s = getStage(o); if (s === "OUT_FOR_DELIVERY") return m > THRESHOLDS.deliveryCritical ? "critical" : m > THRESHOLDS.deliveryWarning ? "warning" : null; if (s === "READY_FOR_DELIVERY" && m > THRESHOLDS.readyWarning) return "warning"; if (!["DELIVERED", "CANCELLED"].includes(s) && minutesSince(o.created_at) > THRESHOLDS.activeLate) return "critical"; return null; };
const errorMessage = (e: unknown) => (e as { response?: { data?: { message?: string } }; message?: string }).response?.data?.message ?? (e as Error).message ?? "تعذر تحميل لوحة العمليات";
const formatTime = (date: Date | null) => date?.toLocaleTimeString("ar", { hour: "2-digit", minute: "2-digit", second: "2-digit" }) ?? "—";

export const OperationsDashboard = () => {
  const [data, setData] = useState<OperationsDashboardResponse>({});
  const [initialLoading, setInitialLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null); const [now, setNow] = useState(Date.now());
  const [branch, setBranch] = useState(""); const [date, setDate] = useState(today());
  const [tab, setTab] = useState<"orders" | "staff" | "fleet" | "alerts">("orders"); const [selected, setSelected] = useState<OperationsOrder | null>(null);
  const [role, setRole] = useState<"all" | OperationalRole>("all"); const [staffFilter, setStaffFilter] = useState<"all" | "active" | "alerts">("all");
  const [fleetStatus, setFleetStatus] = useState<"all" | "available" | "busy">("all"); const [fleetVehicle, setFleetVehicle] = useState("all");
  const [deliverConfirm, setDeliverConfirm] = useState<OperationsOrder | null>(null);
  const [deliveringId, setDeliveringId] = useState<number | null>(null);
  const load = useCallback(async (background = false) => { background ? setRefreshing(true) : setInitialLoading(true); setError(""); try { setData(await operationsService.getDashboard({ date, ...(branch ? { branch_id: Number(branch) } : {}) })); setLastUpdated(new Date()); } catch (e) { setError(errorMessage(e)); } finally { setInitialLoading(false); setRefreshing(false); } }, [branch, date]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const id = window.setInterval(() => { setNow(Date.now()); void load(true); }, 60_000); return () => window.clearInterval(id); }, [load]);
  const orders = data.orders ?? []; const staff = data.staff_summary ?? []; const fleet = data.fleet_summary ?? staff.filter(s => s.operational_role === "delivery_driver"); const k = data.kpis ?? {};
  const stale = lastUpdated ? now - lastUpdated.getTime() > 120_000 : false;
  const kpis = useMemo(() => [
    { label: "الطلبات النشطة", value: k.active_orders ?? orders.filter(o => !["DELIVERED", "CANCELLED"].includes(getStage(o))).length, Icon: Gauge, color: "text-sky-300" },
    { label: "طلبات متأخرة", value: k.late_orders ?? orders.filter(o => risk(o)).length, Icon: ShieldAlert, color: "text-rose-300", critical: true },
    { label: "بانتظار التجميع", value: k.waiting_assembly ?? 0, Icon: Boxes, color: "text-amber-300" },
    { label: "جاهز للدليفري", value: k.ready_for_delivery ?? k.ready_delivery ?? orders.filter(o => getStage(o) === "READY_FOR_DELIVERY").length, Icon: PackageCheck, color: "text-yellow-300", critical: true },
    { label: "خارج للتوصيل", value: k.out_for_delivery ?? orders.filter(o => getStage(o) === "OUT_FOR_DELIVERY").length, Icon: Truck, color: "text-violet-300" },
    { label: "دليفري متاح", value: k.available_drivers ?? fleet.filter(f => !f.current_order && !(f.active_orders_count ?? 0)).length, Icon: UserRoundCheck, color: "text-emerald-300" },
    { label: "دليفري مشغول", value: k.busy_drivers ?? fleet.filter(f => f.current_order || (f.active_orders_count ?? 0) > 0).length, Icon: Bike, color: "text-orange-300" },
    { label: "متوسط التوصيل", value: k.average_delivery_minutes == null ? "—" : `${Math.round(k.average_delivery_minutes)} د`, Icon: Clock3, color: "text-cyan-300" },
  ], [k, orders, fleet]);
  const filteredStaff = staff.filter(s => (role === "all" || s.operational_role === role) && (staffFilter === "all" || (staffFilter === "active" ? s.status?.toUpperCase() === "ACTIVE" : s.has_alert)));
  const filteredFleet = fleet.filter(d => { const busy = Boolean(d.current_order || (d.active_orders_count ?? 0) > 0); return (fleetStatus === "all" || (fleetStatus === "busy" ? busy : !busy)) && (fleetVehicle === "all" || d.vehicle_type === fleetVehicle); });

  const confirmDeliver = (order: OperationsOrder) => setDeliverConfirm(order);

  const handleDeliverConfirm = async () => {
    const order = deliverConfirm; if (!order) return;
    setDeliveringId(order.id); setError('');
    try {
      await orderService.markOrderDelivered(order.id);
      toast.success('تم التسليم', `الطلب #${order.order_number} سلم للزبون`);
      setDeliverConfirm(null);
      void load(true);
    } catch (e) {
      setError(errorMessage(e));
    } finally { setDeliveringId(null); }
  };

  return <main dir="rtl" className="min-h-full bg-slate-950 p-4 text-slate-100 md:p-6">
    <header className="mb-5 flex flex-col gap-4 border-b border-white/10 pb-5 xl:flex-row xl:items-end xl:justify-between">
      <div><p className="mb-1 text-[10px] font-black tracking-[.22em] text-red-400">O2 / LIVE OPERATIONS</p><h1 className="text-2xl font-black md:text-3xl">غرفة متابعة العمليات</h1><p className="mt-1 text-sm text-slate-400">مراقبة تنفيذ الطلبات والموظفين وأسطول التوصيل من شاشة واحدة.</p></div>
      <div className="flex flex-wrap items-end gap-2"><div className={`mb-1 flex items-center gap-2 text-[10px] font-bold ${stale ? "text-amber-300" : "text-emerald-300"}`}><span className={`h-2 w-2 rounded-full ${stale ? "bg-amber-400" : "bg-emerald-400 animate-pulse"}`}/>{stale ? "البيانات قديمة" : "مباشر"} · آخر تحديث {formatTime(lastUpdated)}</div><label className="text-[10px] text-slate-400">الفرع<select aria-label="الفرع" value={branch} onChange={e => setBranch(e.target.value)} className="mt-1 block h-10 min-w-40 rounded-lg border border-white/10 bg-slate-900 px-3 text-xs font-bold text-white outline-none focus:border-red-400"><option value="">كل الفروع</option>{(data.branches ?? []).map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-[10px] text-slate-400">التاريخ<input aria-label="التاريخ" type="date" value={date} onChange={e => setDate(e.target.value)} className="mt-1 block h-10 rounded-lg border border-white/10 bg-slate-900 px-3 text-xs text-white outline-none focus:border-red-400"/></label><button disabled={refreshing} onClick={() => void load(true)} className="flex h-10 items-center gap-2 rounded-lg bg-red-600 px-4 text-xs font-black hover:bg-red-500 disabled:opacity-60 focus:outline-none focus:ring-2 focus:ring-red-300"><RefreshCw size={14} className={refreshing ? "animate-spin" : ""}/> {refreshing ? "جارٍ التحديث" : "تحديث"}</button></div>
    </header>
    <div aria-live="polite">{error && <div className="mb-4 flex items-center justify-between rounded-lg border border-rose-500/40 bg-rose-500/10 p-4 text-sm text-rose-100"><span className="flex items-center gap-2"><AlertTriangle size={18}/>{error}</span><button onClick={() => void load(true)} className="font-black underline">إعادة المحاولة</button></div>}</div>
    <section aria-label="مؤشرات العمليات" className="mb-5 flex gap-2 overflow-x-auto pb-2">{kpis.map(({label,value,Icon,color,critical}) => { const raised = critical && Number(value) > 0; return <article key={label} className={`min-w-[160px] flex-1 border-t-2 p-3 shadow-lg shadow-black/10 ${raised ? "border-rose-400 bg-rose-950/50 ring-1 ring-rose-500/30" : "border-white/15 bg-slate-900/80"}`}><div className="flex items-center justify-between"><span className={`text-[10px] font-bold ${raised ? "text-rose-100" : "text-slate-400"}`}>{label}</span><Icon size={15} className={color}/></div><strong className="mt-2 block text-2xl font-black tabular-nums">{initialLoading ? "…" : value}</strong></article>; })}</section>
    <nav aria-label="أقسام لوحة العمليات" className="mb-4 flex gap-1 overflow-x-auto border-b border-white/10">{([['orders','تنفيذ الطلبات'],['staff','أداء الموظفين'],['fleet','أسطول الدليفري'],['alerts',`التنبيهات (${data.alerts?.length ?? 0})`]] as const).map(([key,label]) => <button key={key} onClick={() => setTab(key)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-xs font-black transition ${tab === key ? 'border-red-500 text-white' : 'border-transparent text-slate-500 hover:text-slate-200'}`}>{label}</button>)}</nav>
    {initialLoading ? <div aria-live="polite" className="flex min-h-72 items-center justify-center gap-3 text-slate-400"><Loader2 className="animate-spin"/> جارٍ تحميل غرفة العمليات...</div> : tab === "orders" ? <section aria-label="مراحل تنفيذ الطلبات" className="grid auto-cols-[minmax(270px,85vw)] grid-flow-col gap-3 overflow-x-auto pb-3 snap-x snap-mandatory xl:auto-cols-auto xl:grid-flow-row xl:grid-cols-5">{STAGES.map(stage => { const list=orders.filter(o=>getStage(o)===stage.key); return <section key={stage.key} className={`snap-start border-t-2 ${stage.accent} bg-slate-900/55`}><div className="flex items-center justify-between border-b border-white/5 p-3"><h2 className="text-xs font-black">{stage.label}</h2><b className="rounded-md bg-white/5 px-2 py-1 text-[10px] tabular-nums">{list.length}</b></div><div className="space-y-2 p-2">{list.length ? list.map(o=><OrderCard key={o.id} order={o} onClick={()=>setSelected(o)} onDeliver={()=>confirmDeliver(o)}/>) : <Empty text="لا توجد طلبات"/>}</div></section>})}</section>
    : tab === "staff" ? <section><Filters role={role} setRole={setRole} state={staffFilter} setState={setStaffFilter}/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filteredStaff.length ? filteredStaff.map(s=><article key={s.id} className={`border-r-2 bg-slate-900 p-4 ${s.has_alert ? "border-rose-500 ring-1 ring-rose-500/20" : "border-red-500"}`}><div className="flex justify-between gap-3"><div><h3 className="font-black">{s.name}</h3><p className="mt-1 text-xs text-slate-500">{ROLE_LABEL[s.operational_role]} · {s.branch?.name ?? "كل الفروع"}</p></div><Status active={s.status?.toUpperCase()==="ACTIVE"}/></div>{s.has_alert && <p className="mt-3 text-[10px] font-bold text-rose-300">يوجد تنبيه تشغيلي يحتاج المراجعة</p>}<div className="mt-4 grid grid-cols-3 gap-2 text-center text-[10px] text-slate-500"><Metric v={s.operational_role === "assembler" ? (s.started_today ?? 0) : (s.active_orders_count ?? 0)} l={s.operational_role === "assembler" ? "بدأ اليوم" : "نشط"}/><Metric v={s.completed_today ?? 0} l="مكتمل اليوم"/><Metric v={s.average_minutes == null ? "—" : `${Math.round(s.average_minutes)} د`} l="المتوسط"/></div></article>) : <Empty text="لا يوجد موظفون مطابقون"/>}</div></section>
    : tab === "fleet" ? <section><div className="mb-4 flex flex-wrap gap-2" aria-label="فلاتر أسطول الدليفري"><select aria-label="حالة المندوب" value={fleetStatus} onChange={e=>setFleetStatus(e.target.value as typeof fleetStatus)} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-xs"><option value="all">كل الحالات ({fleet.length})</option><option value="available">متاح ({fleet.filter(d=>!d.current_order && !(d.active_orders_count??0)).length})</option><option value="busy">مشغول ({fleet.filter(d=>d.current_order || (d.active_orders_count??0)>0).length})</option></select><select aria-label="نوع المركبة" value={fleetVehicle} onChange={e=>setFleetVehicle(e.target.value)} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-xs"><option value="all">كل المركبات</option>{Object.entries(VEHICLE_LABEL).filter(([v])=>v!=="external_driver").map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filteredFleet.length ? filteredFleet.map(d=><article key={d.id} className="bg-slate-900 p-4 ring-1 ring-white/10"><div className="flex items-start justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center bg-slate-800 text-emerald-300"><Bike size={20}/></span><div><h3 className="font-black">{d.name}</h3><p className="text-xs text-slate-500">{VEHICLE_LABEL[d.vehicle_type ?? ''] ?? "مركبة غير محددة"}</p></div></div><Status active={!d.current_order && !(d.active_orders_count ?? 0)} available/></div><div className="mt-4 border-t border-white/5 pt-3 text-xs text-slate-400">{d.current_order ? `الطلب الحالي: #${d.current_order.order_number}` : "لا يوجد طلب حالي"}</div></article>) : <Empty text="لا يوجد دليفري ضمن الفلاتر"/>}</div></section>
    : <section className="space-y-2">{(data.alerts ?? []).length ? data.alerts!.map(a=><article key={a.id} className={`border-r-4 bg-slate-900 p-4 ${a.severity==='critical'?'border-rose-500 bg-rose-950/30':a.severity==='warning'?'border-amber-400':'border-sky-400'}`}><div className="flex items-start gap-3"><AlertTriangle size={18} className={a.severity==='critical'?'text-rose-400':a.severity==='warning'?'text-amber-300':'text-sky-300'}/><div><h3 className="text-sm font-black">{a.title}</h3><p className="mt-1 text-xs text-slate-400">{a.message}</p>{(a.order_number||a.employee_name)&&<p className="mt-2 text-[10px] font-bold text-slate-500">{a.order_number&&`طلب #${a.order_number}`} {a.employee_name&&` · ${a.employee_name}`}</p>}</div></div></article>) : <Empty text="لا توجد تنبيهات تشغيلية"/>}</section>}
    {selected && <OrderDetails order={selected} close={()=>setSelected(null)}/>}
    {deliverConfirm && <div className="fixed inset-0 z-[300] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onClick={e=>{if(e.currentTarget===e.target)setDeliverConfirm(null)}}><div className="w-full max-w-sm rounded-3xl border border-white/10 bg-slate-900 p-6 shadow-2xl"><h2 className="text-lg font-black">تأكيد التسليم</h2><p className="mt-2 text-sm text-slate-400">هل تم تسليم الطلب <b>#{deliverConfirm.order_number}</b> للزبون؟</p><div className="mt-6 flex gap-3"><button onClick={()=>setDeliverConfirm(null)} className="flex-1 rounded-xl bg-slate-800 py-3 text-xs font-black text-slate-300 hover:bg-slate-700">إلغاء</button><button onClick={handleDeliverConfirm} disabled={deliveringId===deliverConfirm.id} className="flex-1 rounded-xl bg-emerald-600 py-3 text-xs font-black text-white hover:bg-emerald-500 disabled:opacity-50">{deliveringId===deliverConfirm.id?<Loader2 size={14} className="animate-spin mx-auto"/>:'تأكيد التسليم'}</button></div></div></div>}
  </main>;
};

const assemblyInfo=(o:OperationsOrder)=>{if(o.assembly_duration_seconds!=null){const m=Math.round(o.assembly_duration_seconds/60);return <span className="text-[10px] text-amber-300">مدة التجميع: {m} د</span>;}if(o.assembly_started_at&&!o.assembled_at){const m=minutesSince(o.assembly_started_at);return <span className="text-[10px] text-sky-300">قيد التجميع منذ: {m} د</span>;}return null;};
const OrderCard=({order,onClick,onDeliver}:{order:OperationsOrder;onClick:()=>void;onDeliver?:()=>void})=>{const r=risk(order),m=getTimer(order),ai=assemblyInfo(order);const outForDelivery=order.status==='OUT_FOR_DELIVERY'&&(order.driver||order.delivery_started_at)&&!order.delivered_at;return <button onClick={onClick} className={`w-full border bg-slate-950/70 p-3 text-right transition hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-red-400 ${r==='critical'?'border-rose-500/70 bg-rose-950/20':r==='warning'?'border-amber-400/50':'border-white/10 hover:border-white/25'}`}><div className="flex items-center justify-between"><b className="text-xs">#{order.order_number}</b>{r&&<span className={`text-[9px] font-black ${r==='critical'?'text-rose-400':'text-amber-300'}`}>{r==='critical'?'متأخر جداً':'يحتاج انتباه'}</span>}</div><h3 className="mt-2 truncate text-sm font-black">{order.customer_name||"عميل نقدي"}</h3><p className="mt-1 truncate text-[10px] text-slate-500">{order.branch?.name||order.branch_name||"فرع غير محدد"}</p>{ai&&<div className="mt-2">{ai}</div>}<div className="mt-3 flex items-end justify-between border-t border-white/5 pt-2"><span className="text-[10px] text-slate-400">{m == null ? "المدة غير متاحة" : <><Clock3 size={11} className="ml-1 inline"/>{m} دقيقة</>} · {order.items_count??order.items?.length??0} صنف</span><b className="text-xs tabular-nums">{Number(order.total??0).toFixed(2)}</b></div>{order.driver&&<p className="mt-2 truncate text-[10px] text-violet-300"><Bike size={11} className="ml-1 inline"/>{order.driver.name} · {VEHICLE_LABEL[order.driver.vehicle_type??'']??''}</p>}{outForDelivery&&onDeliver&&<div className="mt-2" onClick={e=>e.stopPropagation()}><button onClick={onDeliver} className="w-full rounded-lg bg-emerald-600 py-2 text-[11px] font-black text-white hover:bg-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-400">تم تسليم الزبون</button></div>}</button>};
const Empty=({text}:{text:string})=><div className="col-span-full flex min-h-32 flex-col items-center justify-center gap-2 p-5 text-center text-slate-600"><Boxes size={28}/><p className="text-xs font-bold">{text}</p></div>;
const Status=({active,available=false}:{active:boolean;available?:boolean})=><span className={`rounded-md px-2 py-1 text-[9px] font-black ${active?'bg-emerald-500/10 text-emerald-300':'bg-slate-800 text-slate-400'}`}>{active?(available?'متاح':'نشط'):(available?'مشغول':'غير نشط')}</span>;
const Metric=({v,l}:{v:string|number;l:string})=><div className="bg-slate-950/60 p-2"><b className="block text-base text-white">{v}</b>{l}</div>;
const Filters=({role,setRole,state,setState}:{role:"all"|OperationalRole;setRole:(v:"all"|OperationalRole)=>void;state:"all"|"active"|"alerts";setState:(v:"all"|"active"|"alerts")=>void})=><div className="mb-4 flex flex-wrap gap-2"><label className="text-[10px] text-slate-400">الدور<select value={role} onChange={e=>setRole(e.target.value as typeof role)} className="mt-1 block rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-xs text-white"><option value="all">كل الأدوار</option>{Object.entries(ROLE_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[10px] text-slate-400">الحالة<select value={state} onChange={e=>setState(e.target.value as typeof state)} className="mt-1 block rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-xs text-white"><option value="all">كل الحالات</option><option value="active">النشطون</option><option value="alerts">لديهم تنبيه</option></select></label></div>;
const OrderDetails=({order,close}:{order:OperationsOrder;close:()=>void})=>{const closeRef=useRef<HTMLButtonElement>(null);const dialogRef=useRef<HTMLElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;closeRef.current?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close();return}if(e.key==='Tab'){const nodes=dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]), [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);previous?.focus()}},[close]);const timer=getTimer(order);return <div className="fixed inset-0 z-[250] flex justify-end bg-black/70" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><aside ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="order-details-title" className="h-full w-full max-w-md overflow-y-auto border-r border-white/10 bg-slate-950 p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black text-red-400">تفاصيل التنفيذ</p><h2 id="order-details-title" className="mt-1 text-xl font-black">الطلب #{order.order_number}</h2></div><button ref={closeRef} aria-label="إغلاق تفاصيل الطلب" onClick={close} className="bg-slate-900 p-2 text-slate-400 hover:text-white focus:ring-2 focus:ring-red-400"><X size={18}/></button></div><div className="mt-6 space-y-3 text-sm"><p className="flex justify-between border-b border-white/5 pb-3"><span className="text-slate-500">العميل</span><b>{order.customer_name||"عميل نقدي"}</b></p><p className="flex justify-between border-b border-white/5 pb-3"><span className="text-slate-500">المرحلة</span><b>{STAGES.find(s=>s.key===getStage(order))?.label}</b></p><p className="flex justify-between border-b border-white/5 pb-3"><span className="text-slate-500">{getTimerLabel(order)}</span><b>{timer == null ? "غير متاحة" : `${timer} دقيقة`}</b></p><p className="flex justify-between border-b border-white/5 pb-3"><span className="text-slate-500">الإجمالي</span><b>{Number(order.total??0).toFixed(2)}</b></p></div><h3 className="mb-3 mt-7 text-xs font-black text-slate-400">محتويات الطلب</h3><div className="space-y-2">{order.items?.length?order.items.map((i,n)=><div key={i.id??n} className="flex justify-between bg-slate-900 p-3 text-xs"><span>{i.item_name_ar||i.item_name||"صنف"}</span><b>× {i.quantity??1}</b></div>):<Empty text="تفاصيل الأصناف غير متاحة"/>}</div>{order.driver&&<div className="mt-5 border-r-2 border-violet-400 bg-violet-500/10 p-4"><p className="text-[10px] text-violet-300">مندوب التوصيل</p><b className="mt-1 block">{order.driver.name}</b></div>}</aside></div>};

export default OperationsDashboard;